name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint websocket-client zeroconf coverage pytest
      - name: Analysing the code with pylint
        run: |
          pylint -j0 --disable=C0209,C0116,C0115 `find|grep .py$|xargs`
      - name: unitest + coveragecoverage
        run: |
          coverage run --source=./examples,./test -m pytest
          coverage report
