name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint websocket-client zeroconf coverage pytest
          python3 -m pip install --upgrade build
      - name: Analysing the code with pylint
        run: |
          ./build.sh --lint
      - name: unitest + coveragecoverage
        run: |
          export PYTHONPATH=$PYTHONPATH:src/beoremote; coverage run --source=./src,./test -m pytest
          coverage report
      - name: Create Python Package
        run: python3 -m build

      - uses: actions/upload-artifact@v2
        with:
          name: beoremote-halo
          path: dist/beoremote-halo*
