name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint websocket-client zeroconf click coverage pytest
          python3 -m pip install --upgrade build
      - name: unitest + coveragecoverage
        run: ./build.sh --test
      - name: Create Python Package
        run: ./build.sh --pip
      - uses: actions/upload-artifact@v2
        with:
          name: beoremote-halo
          path: dist/*halo*

  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: beoremote-halo
      - name: Verify package - Connect Demo
        run: |
          wget https://github.com/vi/websocat/releases/download/v1.9.0/websocat_linux32_nossl && chmod +x websocat_linux32_nossl
          python3 -m venv env && source env/bin/activate
          python -m pip install beoremote_halo-*-py3-none-any.whl
          timeout --preserve-status 5 echo '{"event":{"type":"system","state":"active"}}' | ./websocat_linux32_nossl -s 8080 --one-message --oneshot &
          timeout --preserve-status 5 beoremote-halo demo --ip localhost
